
services:
  postgres:
    image: postgres:15
    container_name: expertlink-postgres
    environment:
      POSTGRES_DB: expertlink
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - expertlink-network

  redis:
    image: redis:7-alpine
    container_name: expertlink-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - expertlink-network
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:

networks:
  expertlink-network:
    driver: bridge